version: '3.8'
services:
  postgres:
    image: postgres:16.4
    restart: "no"
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresqlNotification/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgresNotification
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
     - app-network
  event-notification:
    image: dockerfile-test-event-notification:0.0.1
    container_name: event-notification
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notificationDb:5432/postgresNotification
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 9092:9092
    networks:
      - app-network

volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge