spring:
  application:
    name: event-notification
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:postgresql://notificationDb:5432/postgresNotification
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations: classpath:schema.sql
      data-locations: classpath:demo_data.sql
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: event-notification
      session-timeout-ms: 15000
      heartbeat-interval-ms: 3000
      max-poll-interval-ms: 300000
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"


springdoc:
  swagger-ui:
    url: /openapi.yaml
server:
  port: 8082
  servlet:
    context-path: /

security:
  jwt:
    secret: 0JzQsNC80LAg0LzRi9C70LAg0YDQsNC80YMs0LAg0JrQsNGA0Lsg0YMg0JrQu9Cw0YDRiyDRg9C60YDQsNC7INC60L7RgNCw0LvRiw==
    access: 3600000

notification:
  delete:
    cron: 0 */1 * * * *